### PR TITLE
separated petri_dish generator and added more documentage to USAGE do…

### PR DESCRIPTION
**Pull request by GALTdea**
…cument, does request_speciment and query_speciment need to have their own resource?

### CODE REVIEW

**Comment by GALTdea** [comment]
Just wrapping my head around some of the concepts but wanted to ask you.  are you planning on having a different generator for queries and request? If so, do we need to have a parent folder for for request_speciment.rb and quary_speciment.rb under initializer? if so, will we need a whole different resource for each one?

**Comment by GALTdea** [comment]
I added the lib/generators/petri_dish  folder to add  templates for views and controllers along with request_specimen & query_specimen?

**Comment by cjilbert504** [comment]
@GALTdea - Sorry for the delayed response. I've read through this and have also been having some other thoughts lately about the design here. I'm sort of thinking that it might be overkill to have a bunch of individual generators for each of the classes (specimens) but let's keep going in this direction and see where we end up.

Just to let you know where my mind is at for the future, I'm thinking what might be better is just one generator that makes one initializer file that enables every specimen option by default and users can opt-out of ones that they don't want to use. To give you a better idea of what I'm thinking the generator would do here's an example:

```ruby
# app/config/initializers/petri_dish.rb

PetriDish.configure do |config|
  config.request_specimen = true
  config.query_specimen = true
  config.another_specimen = false
  config.another_specimen = true
  ...
end
```

I'm going to read through this PR again and merge in unless anything jumps out at me. Thanks for all the info, thoughts, and code!

**Comment by cjilbert504** [comment]
@GALTdea - I've also created an issue over in what will be the actual gem repo [https://github.com/cjilbert504/petri_dish/issues/1](https://github.com/cjilbert504/petri_dish/issues/1) that you can look at to get more of an idea of what I'm thinking. Feel free to comment on it if you have any thoughts or questions!

**Pull request closed without merging**
